# Generated by Django 5.0.6 on 2024-05-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalweb', '0002_entry_topic_delete_text_post_entry_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
    ]
